In [36]:
import basedosdados as bd

In [37]:
project_id = "teste-ic-fairness"
query = """
SELECT
  d.id_inscricao,
  d.cor_raca,
  d.ensino,
  d.estado_civil,
  d.nota_matematica,
  d.sexo,
  d.sigla_uf_prova,
  d.tipo_escola,
  q.q006 AS renda_familiar,
  q.q025 AS tem_internet,
FROM
  `basedosdados.br_inep_enem.microdados` as d

INNER JOIN `basedosdados.br_inep_enem.questionario_socioeconomico_2023` as q
  ON q.id_inscricao = d.id_inscricao

WHERE d.ano = 2023
AND d.nota_matematica IS NOT NULL
AND d.ensino IS NOT NULL
AND d.sigla_uf_prova IS NOT NULL
LIMIT 10000;
"""

df = bd.read_sql(query, billing_project_id=project_id)

print(df)

Downloading: 100%|██████████|
      id_inscricao cor_raca ensino  ... tipo_escola  renda_familiar tem_internet
0     210059804468        5      1  ...           2               C            B
1     210061125487        3      1  ...           2               A            B
2     210060053496        3      1  ...           2               C            A
3     210060837913        1      1  ...           2               K            B
4     210058849767        2      1  ...           2               D            B
...            ...      ...    ...  ...         ...             ...          ...
9995  210059133233        3      1  ...           2               B            B
9996  210059504289        3      1  ...           2               C            B
9997  210059345497        3      1  ...           2               B            B
9998  210060119888        3      1  ...           2               H            B
9999  210061235558        3      1  ...           2               D            B

[10000 rows x 10 columns]

In [38]:
df[df.notnull().all(1)]

      id_inscricao cor_raca ensino  ... tipo_escola  renda_familiar tem_internet
0     210059804468        5      1  ...           2               C            B
1     210061125487        3      1  ...           2               A            B
2     210060053496        3      1  ...           2               C            A
3     210060837913        1      1  ...           2               K            B
4     210058849767        2      1  ...           2               D            B
...            ...      ...    ...  ...         ...             ...          ...
9995  210059133233        3      1  ...           2               B            B
9996  210059504289        3      1  ...           2               C            B
9997  210059345497        3      1  ...           2               B            B
9998  210060119888        3      1  ...           2               H            B
9999  210061235558        3      1  ...           2               D            B

[10000 rows x 10 columns]

In [39]:
df.head()

   id_inscricao cor_raca ensino  ... tipo_escola  renda_familiar tem_internet
0  210059804468        5      1  ...           2               C            B
1  210061125487        3      1  ...           2               A            B
2  210060053496        3      1  ...           2               C            A
3  210060837913        1      1  ...           2               K            B
4  210058849767        2      1  ...           2               D            B

[5 rows x 10 columns]

In [40]:
df.describe()

       nota_matematica
count     10000.000000
mean        495.519540
std         112.373015
min           0.000000
25%         410.475000
50%         482.400000
75%         571.400000
max         931.000000

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_inscricao     10000 non-null  object
 1   cor_raca         10000 non-null  object
 2   ensino           10000 non-null  object
 3   estado_civil     10000 non-null  object
 4   nota_matematica  10000 non-null  float64
 5   sexo             10000 non-null  object
 6   sigla_uf_prova   10000 non-null  object
 7   tipo_escola      10000 non-null  object
 8   renda_familiar   10000 non-null  object
 9   tem_internet     10000 non-null  object
dtypes: float64(1), object(9)
memory usage: 781.4+ KB

In [42]:
df.nunique()

id_inscricao       10000
cor_raca               6
ensino                 2
estado_civil           5
nota_matematica     3646
sexo                   2
sigla_uf_prova        27
tipo_escola            2
renda_familiar        17
tem_internet           2
dtype: int64

In [43]:
import matplotlib.pyplot as plt
import seaborn as sns


# sns.scatterplot(
#     x='sexo',
#     y='nota_matematica',
#     alpha=0.7,
#     data=df,
# )

# dataX = df.groupby('nota_matematica')['sexo'].value_counts()
# plt.figure(figsize=(8, 5))
# plt.hist(dataX, color='#ff5a32', edgecolor='black')

# plt.show()

# dataX

# df.hist(figsize=(20, 20), bins=25)

In [44]:
mapa_raca = {
    "0": 'Não Declarado',
    "1": 'Branca',
    "2": 'Preta',
    "3": 'Parda',
    "4": 'Amarela',
    "5": 'Indígena'
}

mapa_escola = {
    "1": 'Não Respondido',
    "2": 'Pública',
    "3": 'Privada'
}

mapa_internet = {'A': 'Não', 'B': 'Sim'}

# Substituindo no DataFrame
df_visualizacao = df.copy()
df_visualizacao['cor_raca'] = df_visualizacao['cor_raca'].map(mapa_raca)
df_visualizacao['tipo_escola'] = df_visualizacao['tipo_escola'].map(mapa_escola)
df_visualizacao['tem_internet'] = df_visualizacao['tem_internet'].map(mapa_internet)

df_visualizacao.head(10)

# Esse dataFrame facilita a visualização de alguns dados, como raça, tipo da escola, que são atributos importantes.

   id_inscricao  cor_raca ensino  ... tipo_escola  renda_familiar tem_internet
0  210059804468  Indígena      1  ...     Pública               C          Sim
1  210061125487     Parda      1  ...     Pública               A          Sim
2  210060053496     Parda      1  ...     Pública               C          Não
3  210060837913    Branca      1  ...     Pública               K          Sim
4  210058849767     Preta      1  ...     Pública               D          Sim
5  210058061871     Parda      1  ...     Pública               B          Sim
6  210058599526     Parda      1  ...     Pública               B          Sim
7  210059344258  Indígena      1  ...     Pública               C          Sim
8  210060064528     Parda      1  ...     Pública               I          Sim
9  210060204484     Parda      1  ...     Pública               B          Sim

[10 rows x 10 columns]

In [45]:
df[df['id_inscricao'].duplicated()]

Empty DataFrame
Columns: [id_inscricao, cor_raca, ensino, estado_civil, nota_matematica, sexo, sigla_uf_prova, tipo_escola, renda_familiar, tem_internet]
Index: []

In [46]:
df_visualizacao[df_visualizacao['tipo_escola'] == "Privada"].count()

# podemos ver que a minoria dos alunos é de escola particular (o que seria uma vantagem)

id_inscricao       862
cor_raca           862
ensino             862
estado_civil       862
nota_matematica    862
sexo               862
sigla_uf_prova     862
tipo_escola        862
renda_familiar     862
tem_internet       862
dtype: int64

In [47]:
dataEscola = df_visualizacao.groupby('tipo_escola')['nota_matematica'].mean().sort_values(ascending=False)
dataEscola

# aqui vemos também que a escola pública tem uma nota máxima maior em matemática do que a escola privada
# contudo, a privada tem uma média de quase 100 pontos maior que a pública

tipo_escola
Privada    582.979002
Pública    487.269370
Name: nota_matematica, dtype: float64

In [48]:
dataGender = df_visualizacao.groupby('sexo')['nota_matematica'].mean().sort_values(ascending=False)
dataGender

# vemos que a máxima feminina é maior que a máxima masculina
# porém a média masculina é maior que a feminina

sexo
M    519.518301
F    483.784589
Name: nota_matematica, dtype: float64

In [49]:
dataRenda = df_visualizacao.groupby('renda_familiar')['nota_matematica'].mean().sort_values(ascending=False)
dataRenda

# rendas maiores tendém a irem melhores. A renda Q (> 20 sslários minímos) tem o segundo maior máximo e a maior média
# enquanto a renda A (sem renda) tem a pior média e máxima

renda_familiar
O    642.559091
Q    635.179487
L    601.056364
J    592.038793
K    585.113415
N    585.068571
P    580.163636
M    578.206667
I    565.840123
H    552.087234
G    544.692171
F    529.696970
E    519.981692
D    507.201355
C    500.488981
B    466.004816
A    441.279897
Name: nota_matematica, dtype: float64

In [50]:
dataRace = df_visualizacao.groupby('cor_raca')['nota_matematica'].mean().sort_values(ascending=False)
dataRace

cor_raca
Branca           522.473284
Não Declarado    483.858879
Parda            480.075888
Preta            475.953956
Amarela          473.043125
Indígena         465.024194
Name: nota_matematica, dtype: float64

In [51]:
dataState = df_visualizacao.groupby('sigla_uf_prova')['nota_matematica'].mean().sort_values(ascending=False)
dataState

sigla_uf_prova
SP    523.754435
RS    518.828993
SC    516.603830
RJ    514.570853
MG    513.798943
CE    508.572727
ES    506.761878
DF    506.664286
PR    505.303390
PE    496.266606
GO    488.935102
MT    486.479429
SE    485.426519
PB    482.853937
BA    482.824550
MS    478.752448
PI    475.245804
RN    474.398086
AL    472.678286
RR    471.180952
PA    462.487831
RO    462.190323
AM    461.973820
AC    459.131250
AP    457.432877
TO    456.902703
MA    449.437385
Name: nota_matematica, dtype: float64

#### Regressão

Vamos começar com um modelo de Regressão para tentar prever (ou aproximar) a nota da prova de matemática de um aluno que participou do ENEM no ano de 2023. 
<br><br>
O target Y, logicamente, é a nota na prova de matemática.<br>
As outras colunas representam os features (exceto id_inscricao)

Vamos começar com um modelo simples, como um Linear Regression.\
<b>Ainda não iremos calcular métricas de fairness</b>.

In [71]:
# Como no dataset temos diversos valores que são strings, posso usar OneHot Encoder para alguns features com poucas opções, como genero,
# tipo_escola, tem_internet e ensinom que possuem apenas 2 opções
# Para atributos progressivos como renda familiar, podemos considerar um Ordinal Encoder.

# Para atributos como a renda, que possui diversas categorias, talvez um TargetEncoder possa ser útil

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

import numpy as np

np.random.seed(42)

X = df.drop(['nota_matematica', 'id_inscricao'], axis=1)
y = df['nota_matematica']

label_values = ['renda_familiar']
oh_values = ['tipo_escola', 'tem_internet', 'sexo', 'ensino', 'cor_raca', 'estado_civil', 'sigla_uf_prova']
# target_encoder_values = []

full_pipeline = ColumnTransformer(
    transformers=[
        ('label_val', OrdinalEncoder(), label_values),
        ('oh', OneHotEncoder(handle_unknown='ignore'), oh_values),
        # ('target_val', TargetEncoder(), target_encoder_values)
    ],
    remainder='drop',
)

linear_regression_model_pipeline = Pipeline([
    ('preprocessor', full_pipeline),
    ('model', LinearRegression()),
])

splitDf = KFold(random_state=42, shuffle=True)

total_mae = 0
total_rmse = 0
total_r2 = 0
for i, (train_index, test_index) in enumerate(splitDf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    linear_regression_model_pipeline.fit(X_train, y_train)

    # print(f"Treinando no fold {i + 1}")

    preds = linear_regression_model_pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    total_mae += mae
    # print(f"MAE no fold {i + 1}: {mae}")

    rmse = root_mean_squared_error(y_test, preds)
    total_rmse += rmse
    # print(f"RMSE no fold {i + 1}: {rmse}")

    r2 = r2_score(y_test, preds)
    total_r2 += r2
    # print(f"R2 no fold {i + 1}: {r2}")


print(f"\nMédia geral do MAE: {total_mae / 5}")
print(f"Média geral do RMSE: {total_rmse / 5}")
print(f"Média geral do R2: {total_r2 / 5}")

Média geral do MAE: 81.47079314736673
Média geral do RMSE: 103.17129184995807
Média geral do R2: 0.1565887487767425

In [72]:
random_forest_full_pipeline = Pipeline([
    ('preprocessor', full_pipeline),
    ('model', RandomForestRegressor(
        n_estimators=1000,
        max_features=75,
        max_depth=5
    )),
])

total_mae = 0
total_rmse = 0
total_r2 = 0
for i, (train_index, test_index) in enumerate(splitDf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    random_forest_full_pipeline.fit(X_train, y_train)

    # print(f"Treinando no fold {i + 1}")

    preds = random_forest_full_pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    total_mae += mae
    # print(f"MAE no fold {i + 1}: {mae}")

    rmse = root_mean_squared_error(y_test, preds)
    total_rmse += rmse
    # print(f"RMSE no fold {i + 1}: {rmse}")

    r2 = r2_score(y_test, preds)
    total_r2 += r2
    # print(f"R2 no fold {i + 1}: {r2}")


print(f"\nMédia geral do MAE: {total_mae / 5}")
print(f"Média geral do RMSE: {total_rmse / 5}")
print(f"Média geral do R2: {total_r2 / 5}")

Média geral do MAE: 81.9794209017022
Média geral do RMSE: 103.66864360735579
Média geral do R2: 0.14841112503078133

In [ ]:
# param_grid = {
#     'model__n_estimators': [200, 500, 1000],
#     'model__max_features': [50, 75],
#     'model__max_depth': [5, 8, 10]
# }

# grid_search = GridSearchCV(random_forest_full_pipeline, param_grid, cv=splitDf, scoring='r2', return_train_score=True)
# grid_search.fit(X_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('label_val',
                                                                         OrdinalEncoder(),
                                                                         ['renda_familiar']),
                                                                        ('oh',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['tipo_escola',
                                                                          'tem_internet',
                                                                          'sexo',
                                                                          'ensino',
                                                                          'cor_raca']),
                                                                        ('target_val',
                                                                         TargetEncoder(),
                                                                         ['estado_civil',
                                                                          'sigla_uf_prova'])])),
                                       ('model',
                                        RandomForestRegressor(max_depth=5,
                                                              max_features=75,
                                                              n_estimators=1000))]),
             param_grid={'model__max_depth': [5, 8, 10],
                         'model__max_features': [50, 75],
                         'model__n_estimators': [200, 500, 1000]},
             return_train_score=True, scoring='r2')